on:
  push:
    branches:
      - "master"
name: Deploy dtoffff Salesforce Production
jobs:
  deploy:
    environment: Prod
    env:
        SFDX_JWT_KEY: '${{ secrets.SFDX_JWT_KEY }}'
        SFDX_CLIENT_ID: '${{ secrets.SFDX_CLIENT_ID }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: do workaround
        run: rm -rf .git/hooks
      - name: Install Dependencies
        if: steps.npm_cache_id.outputs.cache-hit != 'true'
        run: npm install
      - name: SFDX Auth
        run: |
          echo "test" > server.key
          npx sfdx force:auth:jwt:grant --clientid 3MVG9_kZcLde7U5pDGNMJreMh.tl2TzyHYJMVL9pjYyB3RPJWVoMp1qojQZMbpqilt7JigsbNq36zEEqsLNQf --jwtkeyfile server.key --username dbolton@rlmtraining.com	--setdefaultdevhubusername
          npx sfdx force:org:display --json -u dbolton@rlmtraining.com > sfdx-auth.json
          rm server.key
      - name: Build, Test & Deploy
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: dbolton@rlmtraining.com	
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: destructive-changes
          TEST_LEVEL: RunLocalTests
          WAIT: 200