on:
  push:
    branches:
      - "master"
name: Deploy dtoffff Salesforce Production
jobs:
  deploy:
    environment: Prod
    env:
        SFDX_JWT_KEY: '${{ secrets.SFDX_JWT_KEY }}'
        SFDX_CLIENT_ID: '${{ secrets.SFDX_CLIENT_ID }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: do workaround
        run: rm -rf .git/hooks
      - name: Install Dependencies
        if: steps.npm_cache_id.outputs.cache-hit != 'true'
        run: npm install
      - name: SFDX Auth
        run: |
          echo "-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAqgLM8ktpU+FNRT5sRo4dfNosddy0rnKFYXMYLpVmuBZfREUL
m+4OD6TGtVWkqBxb0hReJ3OTE9iwqUPD0/pDAHps8BwJ55wO+y8n8XKadkcFBpa7
+yZUrsHKA8MTQEGAAVtl3t/NqG/9px7zMMn9OmODCtGTK8eTIaYArOl7ZZv4El4N
7DP32FJlN7OR7AJZCTISXF9CuuIrdlI+WU6JK/DmlKPNRaDx13kw0asjdli/nIMw
wdy772U/p7ubcyXK6VQnpj4AzhkNgEERW3Mi4Ezaf68sqsPOvxHw/f7azpoNpsyz
k1OAlWvGwuPzXlBBdjjWfXL1iOuZ33ajvmntswIDAQABAoIBAFmT3i6wI1Ap/w/E
A0LtsIXPYuu7HYxpFPQys4Qf/h5y00Fia+p99PSzKmvzMy3Mu2imiLGayN0FKJgW
94CidVk0KGAfNezOImqg/xfN/ariYriFBYkgOjBWNT3kNCmAGZUddkCHhZIBaBH9
Ub/cPcvdEPfLUxMXNePd1q9E2lq/hmWD/g2/zkrmXPrP5YNEG+lhvOG31YA5srwU
KAe1ouGESaO3vXIsP1UlWiMCraBcy70QnjZibbpRNU6TUmo5Oy2itvdJXfRoLxXl
PoS+PGrIdGc+/kkMZeXjUJGI3pOBNehvM88vpH5iLXWhJZXYdAuFYuKQbw6IcwYY
gcEdq+kCgYEA2L8mudL+ofNDp0GtUtXYBRg8ErN4sWrdK8SLx7bD8Wu2k3CUVffV
m5MGLcsykhApATtVdVZuZ7iK+ymd3c80ZBcBt2Cp1WMifkiIbt0CC/zWw2j1lOoi
jkuJ7fsprdsE4hRrhCZgUl59OECOb0cu8Jne+I9oaX0Fhjl87FqfOqcCgYEAyMzg
2CT/PtF8+ABDdzx3ih3NGIHCQQmQ+7UiafGcNel/jVSUbaE29tvFa2vajJZhHiCt
bCGBQzWT87rs7fVY5JZchEJI4AArNRbvi17zUsxD1tgwJchOKumfFF/5a4UN8zGb
1SlqdA7krtGzKdCNVzT+Gv0l1uUMLb2CgZ8eshUCgYB80miM73Pw9FVrxyj34WsM
VA6UfoLtOauxfvk4xIpHSE7Wzii+8YE0nREb4j93WpMiwHbQojvmw6JWTns5uBBl
69HzN1nXJ8Y/j6nynpiFKtDLrHBxl/zakaoXQWOZWd6QDE52xlsGVKAsexEMCKSB
rzt3Ta9FwNgjmovU2cOFVQKBgH67qFFjEGICb+BKskoINN5MLsz/4K2RrxreWMkK
/++a3rFBp6iFrp4hWTmSSc6ffs44C5yKjP3xS97xpGYPirpDGEM1Xq9aC+sm/as2
E1a3qz1nFwRRptw4tPl0FYTB5msObW8dA54aZETd/zkt8ncO8C3yhjZaO9SGnl7X
IdV9AoGAOQZ1cynuwf+apxlFewUkpdJBfZA2plSMnWHKPmcrtL6DHDVZgL4ViSav
cLhA7sJCQSb8lSVt4qIcA37piwda9WI8TtQIRnpQoJBTyVkkdsPVGbosDIxKkRTL
TixXSlSqwnxuTacpZJ5ha94ugDODfKAaKo9ZLjXu2FjAC0H4Zlw=
-----END RSA PRIVATE KEY-----" > server.key
          npx sfdx force:auth:jwt:grant --clientid 3MVG9_kZcLde7U5pDGNMJreMh.tl2TzyHYJMVL9pjYyB3RPJWVoMp1qojQZMbpqilt7JigsbNq36zEEqsLNQf --jwtkeyfile server.key --username dbolton@rlmtraining.com	--setdefaultdevhubusername
          npx sfdx force:org:display --json -u dbolton@rlmtraining.com > sfdx-auth.json
          rm server.key
      - name: Build, Test & Deploy
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: dbolton@rlmtraining.com	
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: destructive-changes
          TEST_LEVEL: RunLocalTests
          WAIT: 200