on:
  push:
    branches:
      - "master"
name: Deploy to Salesforce Production
jobs:
  deploy:
    environment: PROD
    env:
        SFDX_JWT_KEY: '${{ secrets.SFDX_JWT_KEY }}'
        SFDX_CLIENT_ID: '${{ secrets.SFDX_CLIENT_ID }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install Dependencies
        if: steps.npm_cache_id.outputs.cache-hit != 'true'
        run: npm install
      - name: install echo
        run: npm install --global echo-cli
      - name: install sfdx
        run:  npm install @salesforce/cli --global
      - name: SFDX Auth 1
        run: echo "${{env.SFDX_JWT_KEY}}" > server.key
      - name: SFDX Auth 2
        run: ls
      - name: SFDX Auth 3
        run: sfdx force:auth:jwt:grant --clientid ${{env.SFDX_CLIENT_ID}} --jwtkeyfile server.key --username dbolton@rlmtraining.com	--setdefaultdevhubusername
      - name: SFDX Auth 4
        run: sfdx force:org:display --json -u dbolton@rlmtraining.com > sfdx-auth.json
      - name: SFDX Auth 5
        run: rm server.key
      - name: Build, Test & Deploy
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: dbolton@rlmtraining.com	
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: destructive-changes
          TEST_LEVEL: NoTestRun
          WAIT: 200