on:
  push:
    branches:
      - "master"
name: Deploy to Salesforce Production
jobs:
  deploy:
    environment: PROD
    env:
        SFDX_JWT_KEY: '${{secrets.SFDX_JWT_KEY}}'
        SFDX_CLIENT_ID: '${{secrets.SFDX_CLIENT_ID}}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install Dependencies
        if: steps.npm_cache_id.outputs.cache-hit != 'true'
        run: npm install
      - name: Install SFDX
        run:  npm install @salesforce/cli --global
      - name: SFDX Step 1 - write key file locally 
        run: echo "${{env.SFDX_JWT_KEY}}" > server.key
      - name: SFDX Step 2 - authenticate
        run: sfdx force:auth:jwt:grant --client-id ${{env.SFDX_CLIENT_ID}} --jwt-key-file server.key --username dbolton@rlmtraining.com	--set-default-dev-hub 
      - name: SFDX Step 3 - write out login details locally
        run: sfdx force:org:display --json -u dbolton@rlmtraining.com > sfdx-auth.json
      - name: SFDX Step 4 - remove key file
        run: rm server.key
      - name: SFDX Step 5 - Build, Test & Deploy using prebuilt action
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: dbolton@rlmtraining.com	
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: destructive-changes
          TEST_LEVEL: NoTestRun
          WAIT: 200